name: FutureChalk Software Inc
favicon: null
layout_spectrum: 0.1717343225609511
typography_spectrum: 0.25428966945037246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8548314196523279
  lightness: 0.6166513215284795
  saturation: 0.22162970155477524
  rhythmicContrast: 0.9539568847976625
purpose: []
